---
title: BA 실습 - 10주차_t-test와 ANOVA
author: Eunju Choe
category: Business Analytics
tags: [Lecture, R, Analytics]
img: ":20230328.png"
date: 2023-03-28 14:25:00 +0900
---
<p align="center"><img src="https://eunju-choe.github.io/assets/img/posts/20230328.png" width='50%'></p>

2021학년도 2학기에 비즈니스 애널리틱스 강의를 수강할 때 작성했던 실습
파일입니다.  
10주차는 t-test와 ANOVA에 대해 학습하였습니다.

## xlsx 파일 불러오기

``` r
# 라이브러리 불러오기
library(readxl)
library(dplyr)

# 엑셀 파일 불러오기
finedust <- read_excel('data/finedust.xlsx')
str(finedust)
```

    ## tibble [3,173 × 3] (S3: tbl_df/tbl/data.frame)
    ##  $ yyyymmdd: chr [1:3173] "전체" "2017-12-31" "2017-12-31" "2017-12-31" ...
    ##  $ area    : chr [1:3173] "평균" "평균" "종로구" "중구" ...
    ##  $ finedust: num [1:3173] 38 63 54 53 60 62 63 69 67 60 ...

``` r
head(finedust)
```

    ## # A tibble: 6 × 3
    ##   yyyymmdd   area   finedust
    ##   <chr>      <chr>     <dbl>
    ## 1 전체       평균         38
    ## 2 2017-12-31 평균         63
    ## 3 2017-12-31 종로구       54
    ## 4 2017-12-31 중구         53
    ## 5 2017-12-31 용산구       60
    ## 6 2017-12-31 성동구       62

``` r
# 새로운 데이터셋 만들기
dust <- finedust %>% filter(area == '성북구' |
                      area == '중구')
head(dust)
```

    ## # A tibble: 6 × 3
    ##   yyyymmdd   area   finedust
    ##   <chr>      <chr>     <dbl>
    ## 1 2017-12-31 중구         53
    ## 2 2017-12-31 성북구       60
    ## 3 2017-12-30 중구        112
    ## 4 2017-12-30 성북구      128
    ## 5 2017-12-29 중구         81
    ## 6 2017-12-29 성북구       95

``` r
# 결측치 확인
sum(is.na(dust))
```

    ## [1] 0

## 통계 검증

### 두 집단 간의 평균 비교 : t.test

``` r
# 두 집단 간 평균 비교 : t.test()
t.test(data = dust, finedust ~ area, var.equal = T)
```

    ## 
    ##  Two Sample t-test
    ## 
    ## data:  finedust by area
    ## t = 2.8347, df = 242, p-value = 0.004975
    ## alternative hypothesis: true difference in means between group 성북구 and group 중구 is not equal to 0
    ## 95 percent confidence interval:
    ##   2.085657 11.586474
    ## sample estimates:
    ## mean in group 성북구   mean in group 중구 
    ##             42.74590             35.90984

#### 결과 해석

이 데이터는 finedust(미세먼지)의 양에 대한 것으로, 성북구와 중구 두
지역의 데이터를 비교한 것이다. t-test 결과 t값은 2.8347이고 p-value는
0.004975로, 이는 유의수준 0.05에서 검정했을 때 귀무가설을 기각할 수
있음을 의미한다. 따라서 성북구와 중구의 평균 차이가 0이 아니다. (=
성북구와 중구의 미세먼지 평균에는 차이가 존재한다.)

``` r
# 정규성 검증 : shapiro.test
shapiro.test(dust$finedust[dust$area == '성북구'])
```

    ## 
    ##  Shapiro-Wilk normality test
    ## 
    ## data:  dust$finedust[dust$area == "성북구"]
    ## W = 0.90358, p-value = 2.497e-07

``` r
shapiro.test(dust$finedust[dust$area == '중구'])
```

    ## 
    ##  Shapiro-Wilk normality test
    ## 
    ## data:  dust$finedust[dust$area == "중구"]
    ## W = 0.91091, p-value = 6.191e-07

#### 결과 해석

shapiro test 결과 p-value가 0.05보다 작아 귀무가설을 기각할 수 있다.
shapiro test의 귀무가설은 ’정규분포를 가진다’이기 때문에, 두 데이터는
정규분포를 따르지 않는다고 할 수 있다.

### 정규분포가 아닐 때엔 wilcox.test

``` r
wilcox.test(data = dust, finedust ~ area)
```

    ## 
    ##  Wilcoxon rank sum test with continuity correction
    ## 
    ## data:  finedust by area
    ## W = 9122.5, p-value = 0.0023
    ## alternative hypothesis: true location shift is not equal to 0

#### 결과 해석

검정 결과 p-value는 0.0023이다. 이는 유의수준 0.05에서 검정했을 때,
귀무가설을 기각할 수 있음을 의미한다. 즉, 두 지역 간의
finedust(미세먼지) 수준에 차이가 있다는 것을 나타내며, 이 차이는
통계적으로 유의미한 것으로 판단된다.

``` r
# 등분산성 검증 : var.test
var.test(data = dust, finedust ~ area)
```

    ## 
    ##  F test to compare two variances
    ## 
    ## data:  finedust by area
    ## F = 1.3339, num df = 121, denom df = 121, p-value = 0.1145
    ## alternative hypothesis: true ratio of variances is not equal to 1
    ## 95 percent confidence interval:
    ##  0.9324219 1.9081099
    ## sample estimates:
    ## ratio of variances 
    ##           1.333853

#### 결과 해석

finedust(미세먼지)의 양에 대한 것이며, 두 개의 지역 간 분산 차이를
비교하는 F test를 수행한 결과이다. 검정 결과 검정통계량 F는 1.3339이며
p-value는 0.1145로, 유의수준 0.05에서 검정했을 때 귀무가설을 기각할 수
없음을 의미한다. 따라서, 두 지역 간의 분산 차이가 통계적으로 유의하지
않다는 것을 나타낸다.

### 세 집단 간의 평균 비교 : ANOVA

``` r
data(iris)
str(iris)
```

    ## 'data.frame':    150 obs. of  5 variables:
    ##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
    ##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
    ##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
    ##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
    ##  $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

``` r
out <- aov(data = iris, Sepal.Width ~ Species)
summary(out)
```

    ##              Df Sum Sq Mean Sq F value Pr(>F)    
    ## Species       2  11.35   5.672   49.16 <2e-16 ***
    ## Residuals   147  16.96   0.115                   
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

#### 결과 해석

Sepal.Width를 Species 별로 분석한 일원분산분석(one-way ANOVA)의 결과로,
Species 변수는 Sepal.Width에 유의미한 영향을 끼치는 것으로 나타난다.

### 사후 검정

``` r
TukeyHSD(out)
```

    ##   Tukey multiple comparisons of means
    ##     95% family-wise confidence level
    ## 
    ## Fit: aov(formula = Sepal.Width ~ Species, data = iris)
    ## 
    ## $Species
    ##                        diff         lwr        upr     p adj
    ## versicolor-setosa    -0.658 -0.81885528 -0.4971447 0.0000000
    ## virginica-setosa     -0.454 -0.61485528 -0.2931447 0.0000000
    ## virginica-versicolor  0.204  0.04314472  0.3648553 0.0087802

#### 결과 해석

분석 결과, 각 종(species) 간의 꽃받침 너비 차이가 모두 유의미하다는 것을
나타낸다.

- versicolor-setosa 간의 꽃받침 너비 차이: -0.658, p-value: 0
- virginica-setosa 간의 꽃받침 너비 차이: -0.454, p-value: 0
- virginica-versicolor 간의 꽃받침 너비 차이: 0.204, p-value: 0.0088

위의 결과를 통해, 각 종별로 꽃받침 너비에 유의미한 차이가 있음을 알 수
있다.

``` r
# 등분산성 확인 - 3개 이상 : bartlett test
bartlett.test(data = iris, Sepal.Width ~ Species)
```

    ## 
    ##  Bartlett test of homogeneity of variances
    ## 
    ## data:  Sepal.Width by Species
    ## Bartlett's K-squared = 2.0911, df = 2, p-value = 0.3515

#### 결과 해석

검정 결과 p-value 값이 0.3515로, 유의수준 0.05보다 크므로 귀무가설을
기각할 수 없다. 따라서 등분산성을 가정할 수 있다.

### 정규성을 만족하지 않는 경우 : kruskal.test

``` r
# 정규성을 따르지 않는다고 가정
kruskal.test(data = iris, Sepal.Width ~ Species)
```

    ## 
    ##  Kruskal-Wallis rank sum test
    ## 
    ## data:  Sepal.Width by Species
    ## Kruskal-Wallis chi-squared = 63.571, df = 2, p-value = 1.569e-14

### 등분산성을 만족하지 않는 경우 : welch’stest

``` r
# 등분산성을 만족하지 않는다고 가정
oneway.test(data = iris, Sepal.Width ~ Species, var.equal = F)
```

    ## 
    ##  One-way analysis of means (not assuming equal variances)
    ## 
    ## data:  Sepal.Width and Species
    ## F = 45.012, num df = 2.000, denom df = 97.402, p-value = 1.433e-14
