---
title: 키오스크 이용 경험이 지속 사용 의도에 미치는 영향 분석
author: Eunju Choe
category: Project
tags: [Marketing, Research, R, Statistics, Survey, Lecture]
img: ":20230407.png"
date: 2023-04-07 20:53:00 +0900
---
<p align="center"><img src="https://eunju-choe.github.io/assets/img/posts/20230407.png" width='50%'></p>

오늘은 마케팅조사론을 수강할 당시 ’키오스크 이용 경험이 매장 지속 사용 의도에 미치는 영향’을 주제로 실시한 팀 프로젝트를 정리해보려고 합니다. 프로젝트는 가설을 설정하여 설문조사를 기획하여 실시하고, 결과를분석하여 가설을 검증하는 방식으로 진행하였습니다.

# 1. 프로젝트 개요

## 1.1. 주제 선정 배경

키오스크(Kiosk)는 정보 서비스와 업무의 무인 자동화를 위해 공공장소에
설치된 무인 단말기로, 본 연구에서는 식당이나 카페 등의 음식점에서
서비스를 이용할 때 사용하는 ‘무인 주문 기계’로 그 의미를 한정하였습니다.

코로나19의 영향으로 비대면 주문의 수요가 증가하고, 인건비 절감 등의
이점으로 키오스크는 빠르게 보편화되었습니다. 그 결과 2021년 음식점의
키오스크 전체 보급률은 4.5%(약 3만 대)로 2020년 대비 45% 증가하였습니다.
이번 프로젝트에서는 빠르게 확산되는 키오스크가 매장 재방문율에
미치는지를 알고자 하였습니다. 따라서 키오스크가 가지는 특성을 ’과정
품질’, ‘결과 품질’, ’환경 품질’로 나누어, 그 품질이 각각 서비스 이용자의
경험 가치와 지속 사용 의도에 어떤 영향을 미치는지 분석하였습니다.

### 1.1.1.용어 설명

- 서비스 품질 특성
  - 과정 품질 : 서비스 전달 과정에서 서비스가 어떻게 제공되고, 얼마나
    프로세스가 용이한지에 대한 평가
  - 결과 품질 : 서비스나 구매가 이루어진 후 그 결과에 대한 평가
  - 환경 품질 : 키오스크의 물리적 환경에 해당하는 품질에 대한 평가
    (접근성, 심미성 등)
- 경험 가치 : 키오스크 사용 경험을 통해 지각한 혜택과 선호도
- 지속 사용 의도 : 키오스크를 이용한 후 미래에 다시 이용하고자 하는 신념
  또는 의지

## 1.2. 가설 설정

이번 프로젝트에서는 ‘서비스 이용자의 키오스크 경험 가치는 서비스에 대한
이용자의 만족도에 영향을 줄 것이다.’, ’이용자의 만족도는 서비스 지속
사용 의도에 영향을 미칠 것이다.’라는 두 가지 가설을 검증하고자
하였습니다. 이를 검증하기 위한 세부적인 가설은 다음과 같습니다.

- 키오스크의 품질 특성은 경험 가치에 유의한 영향을 미칠 것이다.
  - 키오스크 과정 품질은 경험 가치에 정(+)의 영향을 미칠 것이다.
  - 키오스크 결과 품질은 경험 가치에 정(+)의 영향을 미칠 것이다.
  - 키오스크 환경 품질은 경험 가치에 정(+)의 영향을 미칠 것이다.
- 키오스크 이용에 대한 경험 가치는 만족에 유의한 정(+)의 영향을 미칠
  것이다.
- 키오스크에 대한 만족은 지속 사용 의도에 유의한 정(+)의 영향을 미칠
  것이다.

## 1.3. 프로젝트 설계

### 1.3.1. 프로젝트 프로세스

우선 품질 특성(과정 품질, 결과 품질, 환경 품질), 경험 가치, 만족, 지속
사용 의도를 측정하기 위해 설문지를 만들고 설문조사를 실시하였습니다.
설문조사는 2022년 6월 2일부터 6월 3일까지 구글 폼을 이용하여
진행되었으며, 총 47개의 답변을 수집할 수 있었습니다. 설문 조사 결과를
분석하기에 앞서 크론바하 알파 계수를 활용하여 신뢰도를 확인하고, 가설
검증을 실시하였습니다.

### 1.3.2. 설문지 구성
![png](https://eunju-choe.github.io/assets/img/posts/20230407/survey.png)

설문조사에서 사용된 설문 문항은 위의 사진과 같습니다.

------------------------------------------------------------------------

# 2. 설문 결과 분석

설문 결과를 분석하기 위해서 R을 사용하였습니다.

## 2.1. 데이터 불러오기

``` r
# 라이브러리 불러오기
library(psych)

# 데이터 불러오기
data <- read.csv('response.csv')

# 20대의 설문 결과만 사용
data <- data[data$age<30, ]
```

설문 결과가 저장된 파일을 먼저 불러왔습니다. 설문 결과 1명을 제외한 모든
응답자가 20대였기때문에, 분석 대상을 20대로 한정하였습니다. 이를 위해
20대 데이터만 남겨두었습니다.

## 2.2. 신뢰도 분석

크론바하 알파 계수(Cronbach’s alpha)는 하나의 특성을 측정하기 위해 여러
개의 문항으로 이루어진 평가 도구의 신뢰도를 측정하는 방법 중 하나입니다.
크론바하 알파는 0에서 1 사이의 값으로 나타나며, 1에 가까울수록 평가
도구의 신뢰도가 높다는 것을 의미합니다. 일반적으로 0.7 이상인 경우
신뢰성이 높은 것으로 여겨지고, 0.9 이상인 경우 매우 높은 신뢰성을 갖는
것으로 여겨집니다. 신뢰성이 낮으면 평가 도구를 사용하여 얻은 결과가
일관성이 없을 가능성이 높으므로 사용에 유의해야합니다. 설문조사를 통해
수집한 변수가 각각 신뢰할 수 있는지 크론바하 알파 계수를 활용하여
확인하였습니다.

``` r
# 경험 가치의 신뢰도 분석
alpha(data[, c('value1', 'value2', 'value3')])
```

    ## 
    ## Reliability analysis   
    ## Call: alpha(x = data[, c("value1", "value2", "value3")])
    ## 
    ##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
    ##       0.77      0.77    0.74      0.53 3.4 0.061  3.7 0.92     0.44
    ## 
    ##     95% confidence boundaries 
    ##          lower alpha upper
    ## Feldt     0.62  0.77  0.86
    ## Duhachek  0.65  0.77  0.89
    ## 
    ##  Reliability if an item is dropped:
    ##        raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
    ## value1      0.87      0.87    0.76      0.76 6.5    0.039    NA  0.76
    ## value2      0.56      0.56    0.39      0.39 1.3    0.128    NA  0.39
    ## value3      0.61      0.61    0.44      0.44 1.5    0.115    NA  0.44
    ## 
    ##  Item statistics 
    ##         n raw.r std.r r.cor r.drop mean  sd
    ## value1 47  0.75  0.73  0.48   0.44  3.7 1.2
    ## value2 47  0.88  0.88  0.84   0.71  3.8 1.1
    ## value3 47  0.86  0.87  0.81   0.67  3.7 1.1
    ## 
    ## Non missing response frequency for each item
    ##           1    2    3    4    5 miss
    ## value1 0.06 0.09 0.19 0.36 0.30    0
    ## value2 0.00 0.17 0.19 0.30 0.34    0
    ## value3 0.02 0.13 0.30 0.28 0.28    0

세 개의 항목으로 이루어진 경험 가치의 신뢰도는 alpha가 0.77로 항목들의
내재적인 일관성을 확인할 수 있습니다. 즉 이 평가 척도는 신뢰성이 높다고
할 수 있습니다.

``` r
# 과정 품질의 신뢰도 분석
alpha(data[, c('process_order1', 'process_order2', 'process_order3', 'process_order4',
                 'process_info1', 'process_info2', 'process_info3', 'process_info4')])
```

    ## 
    ## Reliability analysis   
    ## Call: alpha(x = data[, c("process_order1", "process_order2", "process_order3", 
    ##     "process_order4", "process_info1", "process_info2", "process_info3", 
    ##     "process_info4")])
    ## 
    ##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
    ##       0.75      0.75    0.83      0.27   3 0.057  3.3 0.72     0.22
    ## 
    ##     95% confidence boundaries 
    ##          lower alpha upper
    ## Feldt     0.62  0.75  0.84
    ## Duhachek  0.63  0.75  0.86
    ## 
    ##  Reliability if an item is dropped:
    ##                raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
    ## process_order1      0.67      0.67    0.75      0.23 2.0    0.074 0.046  0.22
    ## process_order2      0.70      0.71    0.79      0.26 2.4    0.067 0.048  0.22
    ## process_order3      0.70      0.70    0.78      0.25 2.4    0.069 0.056  0.21
    ## process_order4      0.71      0.72    0.80      0.27 2.5    0.065 0.051  0.23
    ## process_info1       0.76      0.76    0.84      0.31 3.2    0.056 0.064  0.23
    ## process_info2       0.73      0.73    0.79      0.28 2.8    0.059 0.064  0.23
    ## process_info3       0.70      0.71    0.79      0.26 2.4    0.068 0.072  0.12
    ## process_info4       0.76      0.77    0.83      0.32 3.3    0.053 0.054  0.29
    ## 
    ##  Item statistics 
    ##                 n raw.r std.r r.cor r.drop mean  sd
    ## process_order1 47  0.79  0.80  0.82   0.71  4.0 1.0
    ## process_order2 47  0.66  0.67  0.65   0.52  3.8 1.2
    ## process_order3 47  0.70  0.69  0.66   0.55  3.3 1.3
    ## process_order4 47  0.63  0.63  0.59   0.46  3.4 1.3
    ## process_info1  47  0.42  0.42  0.29   0.23  3.0 1.2
    ## process_info2  47  0.55  0.55  0.49   0.38  2.8 1.2
    ## process_info3  47  0.68  0.67  0.62   0.53  2.9 1.3
    ## process_info4  47  0.39  0.39  0.28   0.19  2.9 1.2
    ## 
    ## Non missing response frequency for each item
    ##                   1    2    3    4    5 miss
    ## process_order1 0.02 0.09 0.15 0.36 0.38    0
    ## process_order2 0.02 0.19 0.11 0.34 0.34    0
    ## process_order3 0.09 0.23 0.23 0.23 0.21    0
    ## process_order4 0.06 0.21 0.21 0.23 0.28    0
    ## process_info1  0.11 0.26 0.28 0.26 0.11    0
    ## process_info2  0.15 0.30 0.23 0.23 0.09    0
    ## process_info3  0.13 0.32 0.23 0.17 0.15    0
    ## process_info4  0.13 0.32 0.21 0.26 0.09    0

8개의 항목으로 이루어진 과정 품질의 신뢰도는 alpha가 0.75로, 평가 척도의
신뢰성이 높다고 판단할 수 있습니다.

``` r
# 결과 품질의 신뢰도 분석
alpha(data[, c('outcome1', 'outcome2', 'outcome3', 'outcome4', 'outcome5')])
```

    ## 
    ## Reliability analysis   
    ## Call: alpha(x = data[, c("outcome1", "outcome2", "outcome3", "outcome4", 
    ##     "outcome5")])
    ## 
    ##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean sd median_r
    ##       0.88      0.88    0.89      0.59 7.3 0.029  3.6  1     0.58
    ## 
    ##     95% confidence boundaries 
    ##          lower alpha upper
    ## Feldt     0.81  0.88  0.93
    ## Duhachek  0.82  0.88  0.93
    ## 
    ##  Reliability if an item is dropped:
    ##          raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
    ## outcome1      0.85      0.86    0.83      0.60 6.0    0.035 0.0055  0.58
    ## outcome2      0.83      0.84    0.81      0.56 5.1    0.040 0.0114  0.58
    ## outcome3      0.87      0.87    0.88      0.63 6.9    0.031 0.0228  0.66
    ## outcome4      0.87      0.87    0.86      0.63 6.7    0.032 0.0181  0.62
    ## outcome5      0.83      0.83    0.84      0.56 5.0    0.041 0.0236  0.53
    ## 
    ##  Item statistics 
    ##           n raw.r std.r r.cor r.drop mean  sd
    ## outcome1 47  0.82  0.81  0.80   0.71  3.7 1.2
    ## outcome2 47  0.88  0.87  0.87   0.79  3.4 1.3
    ## outcome3 47  0.77  0.77  0.66   0.63  3.6 1.3
    ## outcome4 47  0.77  0.78  0.71   0.65  3.6 1.2
    ## outcome5 47  0.87  0.88  0.84   0.80  3.8 1.1
    ## 
    ## Non missing response frequency for each item
    ##             1    2    3    4    5 miss
    ## outcome1 0.09 0.11 0.13 0.40 0.28    0
    ## outcome2 0.06 0.26 0.15 0.26 0.28    0
    ## outcome3 0.09 0.15 0.13 0.32 0.32    0
    ## outcome4 0.04 0.19 0.17 0.32 0.28    0
    ## outcome5 0.00 0.19 0.19 0.26 0.36    0

5개의 항목으로 이루어진 결과 품질의 신뢰도는 alpha가 0.88로, 높은
신뢰도를 가지고 있다고 판단할 수 있습니다.

``` r
# 환경 품질의 신뢰도 분석 (전체)
alpha(data[, c('environment1', 'environment2', 'environment3', 'environment4',
               'environment5', 'environment6', 'environment7')])
```



    ## 
    ## Reliability analysis   
    ## Call: alpha(x = data[, c("environment1", "environment2", "environment3", 
    ##     "environment4", "environment5", "environment6", "environment7")])
    ## 
    ##   raw_alpha std.alpha G6(smc) average_r  S/N  ase mean  sd median_r
    ##       0.46      0.49    0.63      0.12 0.97 0.12  3.1 0.6     0.12
    ## 
    ##     95% confidence boundaries 
    ##          lower alpha upper
    ## Feldt     0.19  0.46  0.67
    ## Duhachek  0.22  0.46  0.70
    ## 
    ##  Reliability if an item is dropped:
    ##              raw_alpha std.alpha G6(smc) average_r  S/N alpha se var.r med.r
    ## environment1      0.30      0.29    0.48     0.062 0.40     0.16 0.080 0.026
    ## environment2      0.46      0.46    0.56     0.125 0.86     0.12 0.052 0.140
    ## environment3      0.43      0.42    0.52     0.110 0.74     0.13 0.048 0.140
    ## environment4      0.39      0.43    0.61     0.112 0.76     0.14 0.107 0.073
    ## environment5      0.53      0.57    0.69     0.182 1.34     0.11 0.090 0.154
    ## environment6      0.40      0.46    0.61     0.125 0.86     0.14 0.096 0.073
    ## environment7      0.43      0.49    0.61     0.137 0.95     0.13 0.085 0.122
    ## 
    ##  Item statistics 
    ##               n raw.r std.r  r.cor r.drop mean  sd
    ## environment1 47  0.69  0.75  0.756  0.524  2.2 1.0
    ## environment2 47  0.39  0.48  0.463  0.133  3.4 1.1
    ## environment3 47  0.45  0.55  0.568  0.214  3.5 1.1
    ## environment4 47  0.52  0.54  0.380  0.290  3.0 1.1
    ## environment5 47  0.28  0.24 -0.031 -0.019  3.3 1.2
    ## environment6 47  0.59  0.48  0.340  0.259  3.0 1.6
    ## environment7 47  0.53  0.43  0.297  0.217  3.0 1.4
    ## 
    ## Non missing response frequency for each item
    ##                 1    2    3    4    5 miss
    ## environment1 0.23 0.51 0.15 0.06 0.04    0
    ## environment2 0.09 0.11 0.21 0.47 0.13    0
    ## environment3 0.04 0.15 0.21 0.45 0.15    0
    ## environment4 0.06 0.32 0.28 0.26 0.09    0
    ## environment5 0.09 0.26 0.06 0.47 0.13    0
    ## environment6 0.26 0.17 0.09 0.26 0.23    0
    ## environment7 0.19 0.23 0.11 0.30 0.17    0

7개 항목으로 구성된 환경 품질의 경우에는 alpha가 0.46으로 신뢰할 수
없었습니다. 따라서 불편했던 경험을 묻는 질문(environment5 \~
environment7)을 제외해보았습니다.

``` r
# 환경 품질의 신뢰도 분석 (일부 제외)
alpha(data[, c('environment1', 'environment2', 'environment3', 'environment4')])
```

    ## 
    ## Reliability analysis   
    ## Call: alpha(x = data[, c("environment1", "environment2", "environment3", 
    ##     "environment4")])
    ## 
    ##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
    ##       0.71      0.71    0.74      0.38 2.5 0.071    3 0.78      0.4
    ## 
    ##     95% confidence boundaries 
    ##          lower alpha upper
    ## Feldt     0.54  0.71  0.82
    ## Duhachek  0.57  0.71  0.85
    ## 
    ##  Reliability if an item is dropped:
    ##              raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
    ## environment1      0.56      0.56    0.62      0.30 1.3    0.115 0.157  0.12
    ## environment2      0.60      0.61    0.58      0.34 1.6    0.103 0.055  0.32
    ## environment3      0.53      0.54    0.51      0.28 1.2    0.123 0.055  0.32
    ## environment4      0.83      0.83    0.78      0.61 4.7    0.044 0.018  0.59
    ## 
    ##  Item statistics 
    ##               n raw.r std.r r.cor r.drop mean  sd
    ## environment1 47  0.81  0.82  0.72   0.64  2.2 1.0
    ## environment2 47  0.78  0.77  0.74   0.56  3.4 1.1
    ## environment3 47  0.84  0.84  0.83   0.68  3.5 1.1
    ## environment4 47  0.50  0.50  0.23   0.17  3.0 1.1
    ## 
    ## Non missing response frequency for each item
    ##                 1    2    3    4    5 miss
    ## environment1 0.23 0.51 0.15 0.06 0.04    0
    ## environment2 0.09 0.11 0.21 0.47 0.13    0
    ## environment3 0.04 0.15 0.21 0.45 0.15    0
    ## environment4 0.06 0.32 0.28 0.26 0.09    0

4개의 항목만 사용한 결과 alpha가 0.71로 신뢰도를 확보할 수 있었습니다.
따라서 가설 검증을 할 때 4가지 항목만 활용하기로 하였습니다.

``` r
# 만족도의 신뢰도 분석
alpha(data[, c('satisfaction1', 'satisfaction2', 'satisfaction3', 'satisfaction4')])
```

    ## 
    ## Reliability analysis   
    ## Call: alpha(x = data[, c("satisfaction1", "satisfaction2", "satisfaction3", 
    ##     "satisfaction4")])
    ## 
    ##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
    ##        0.9      0.92     0.9      0.74  11 0.023  3.7 0.89     0.72
    ## 
    ##     95% confidence boundaries 
    ##          lower alpha upper
    ## Feldt     0.85   0.9  0.94
    ## Duhachek  0.86   0.9  0.95
    ## 
    ##  Reliability if an item is dropped:
    ##               raw_alpha std.alpha G6(smc) average_r  S/N alpha se  var.r med.r
    ## satisfaction1      0.92      0.92    0.89      0.80 11.8    0.021 0.0030  0.81
    ## satisfaction2      0.87      0.89    0.86      0.74  8.5    0.032 0.0080  0.70
    ## satisfaction3      0.85      0.87    0.82      0.69  6.8    0.035 0.0019  0.70
    ## satisfaction4      0.87      0.88    0.84      0.71  7.5    0.034 0.0077  0.68
    ## 
    ##  Item statistics 
    ##                n raw.r std.r r.cor r.drop mean   sd
    ## satisfaction1 47  0.87  0.84  0.75   0.72  3.7 1.26
    ## satisfaction2 47  0.89  0.89  0.85   0.80  3.5 1.00
    ## satisfaction3 47  0.92  0.93  0.92   0.86  3.8 0.90
    ## satisfaction4 47  0.90  0.91  0.89   0.84  3.9 0.84
    ## 
    ## Non missing response frequency for each item
    ##                  1    2    3    4    5 miss
    ## satisfaction1 0.04 0.17 0.19 0.21 0.38    0
    ## satisfaction2 0.02 0.15 0.28 0.40 0.15    0
    ## satisfaction3 0.02 0.04 0.26 0.47 0.21    0
    ## satisfaction4 0.00 0.06 0.19 0.49 0.26    0

4개의 항목으로 이루어진 만족도의 신뢰도는 alpha가 0.92로 매우 높고,
항목들 간의 상관관계도 높게 나타났습니다. 따라서 신뢰성이 높다고 할 수
있습니다.

``` r
# 지속 사용 의도의 신뢰도 분석
alpha(data[, c('continuous1', 'continuous2', 'continuous3')])
```

    ## 
    ## Reliability analysis   
    ## Call: alpha(x = data[, c("continuous1", "continuous2", "continuous3")])
    ## 
    ##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
    ##       0.61      0.58    0.67      0.31 1.4 0.094  3.7 0.92     0.12
    ## 
    ##     95% confidence boundaries 
    ##          lower alpha upper
    ## Feldt     0.37  0.61  0.77
    ## Duhachek  0.43  0.61  0.80
    ## 
    ##  Reliability if an item is dropped:
    ##             raw_alpha std.alpha G6(smc) average_r  S/N alpha se var.r med.r
    ## continuous1     0.019      0.02    0.01      0.01 0.02     0.28    NA  0.01
    ## continuous2     0.203      0.21    0.12      0.12 0.26     0.23    NA  0.12
    ## continuous3     0.898      0.90    0.82      0.82 8.84     0.03    NA  0.82
    ## 
    ##  Item statistics 
    ##              n raw.r std.r r.cor r.drop mean  sd
    ## continuous1 47  0.90  0.87 0.890  0.704  3.7 1.3
    ## continuous2 47  0.86  0.83 0.829  0.610  3.3 1.3
    ## continuous3 47  0.44  0.51 0.089  0.066  4.1 1.0
    ## 
    ## Non missing response frequency for each item
    ##                1    2    3    4    5 miss
    ## continuous1 0.06 0.17 0.15 0.26 0.36    0
    ## continuous2 0.06 0.23 0.28 0.15 0.28    0
    ## continuous3 0.04 0.04 0.09 0.38 0.45    0

3개의 항목으로 이루어진 지속 사용 의도는 alpha가 0.61로, 일반적으로는
약간 낮은 신뢰도를 나타냅니다. 이번 프로젝트에서는 alpha의 한계치를
0.6으로 설정하여, 지속 사용 의도를 3가지 항목 모두 사용하기로
하였습니다.

### 2.2.1. 변수 정의

신뢰도 분석 결과를 바탕으로 가설 검증에 사용할 변수를 정의하였습니다.
변수는 항목별 점수의 평균으로 계산하였습니다.

``` r
# 경험 가치
value <- (data$value1 + data$value2 + data$value3)/3
# 과정 품질
process <- (data$process_order1 + data$process_order2 + 
              data$process_order3 + data$process_order4 +
              data$process_info1 + data$process_info2 + 
              data$process_info3 + data$process_info4)/8
# 결과 품질
outcome <- (data$outcome1 + data$outcome2 + data$outcome3 + 
              data$outcome4 + data$outcome5)/5
# 환경 품질
environment <- (data$environment1 + data$environment2 + 
                  data$environment3 + data$environment4)/4
# 만족도
satisfaction <- (data$satisfaction1 + data$satisfaction2 + 
                   data$satisfaction3 + data$satisfaction4)/4
# 지속 사용 의도
continuous <- (data$continuous1 + data$continuous2 + data$continuous3)/3
```

## 2.3. 가설 검증

앞서 정의한 변수를 바탕으로 가설을 하나씩 검증해보도록 하겠습니다.
### 2.3.1. 키오스크의 과정 품질은 경험 가치에 정(+)의 영향을 미칠 것이다.
키오스크의 과정 품질(process)이 경험 가치(value)에 미치는 영향을
검증하기 위해 단순 선형 회귀를 사용하였습니다.

``` r
verf1 <- lm(value ~ process)
summary(verf1)
```

    ## 
    ## Call:
    ## lm(formula = value ~ process)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1.60700 -0.44634  0.08232  0.59966  1.35833 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)   1.3416     0.5188   2.586    0.013 *  
    ## process       0.7360     0.1557   4.728 2.26e-05 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.764 on 45 degrees of freedom
    ## Multiple R-squared:  0.3319, Adjusted R-squared:  0.3171 
    ## F-statistic: 22.36 on 1 and 45 DF,  p-value: 2.259e-05

단순회귀분석 결과 독립변수인 process가 종속변수인 value에 유의한 영향을
미치는 것을 알 수 있습니다. 회귀계수는 0.736으로 process 값이 1 증가할
때마다 value의 평균값이 0.736 증가함을 의미합니다. 또한 모델의 설명력인
Adjusted R-squared는 0.3171로 독립변수가 종속변수의 변동을 약 31.71%
정도 설명할 수 있음을 의미합니다. 따라서 키오스크의 과정 품질은 경험
가치에 정(+)의 영향을 미친다고 할 수 있습니다.

### 2.3.2. 키오스크의 결과 품질은 경험 가치에 정(+)의 영향을 미칠 것이다.

키오스크의 결과 품질(outcome)이 경험 가치(value)에 미치는 영향을
검증하기 위해 단순 선형 회귀를 사용하였습니다.

``` r
verf2 <- lm(value ~ outcome)
summary(verf2)
```

    ## 
    ## Call:
    ## lm(formula = value ~ outcome)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1.15463 -0.32726  0.00608  0.33048  1.29775 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)   1.2558     0.3331   3.770 0.000473 ***
    ## outcome       0.6845     0.0885   7.735 8.41e-10 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.6125 on 45 degrees of freedom
    ## Multiple R-squared:  0.5707, Adjusted R-squared:  0.5612 
    ## F-statistic: 59.82 on 1 and 45 DF,  p-value: 8.412e-10

단순회귀분석 결과 독립변수인 outcome이 종속변수인 value에 유의한 영향을
미치는 것을 알 수 있습니다. 또한 회귀계수는 0.6845, Adjusted R-squared는
0.5707로 나타났습니다. 따라서 키오스크의 결과 품질은 경험 가치에 정(+)의
영향을 미친다고 할 수 있습니다.

### 2.3.3. 키오스크의 환경 품질은 경험 가치에 정(+)의 영향을 미칠 것이다.

키오스크의 환경 품질(environment)이 경험 가치(value)에 미치는 영향을
검증하기 위해 단순 선형 회귀를 사용하였습니다.

``` r
verf3 <- lm(value ~ environment)
summary(verf3)
```

    ## 
    ## Call:
    ## lm(formula = value ~ environment)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1.47497 -0.53624  0.00787  0.46376  1.64574 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)   1.5344     0.4335   3.539 0.000945 ***
    ## environment   0.7279     0.1388   5.245 4.05e-06 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.7364 on 45 degrees of freedom
    ## Multiple R-squared:  0.3794, Adjusted R-squared:  0.3656 
    ## F-statistic: 27.51 on 1 and 45 DF,  p-value: 4.047e-06

단순회귀분석 결과 독립변수인 environment가 종속변수인 value에 유의한
영향을 미치는 것을 알 수 있습니다. 회귀계수는 0.7279, Adjusted
R-squared는 0.3656으로 나타났습니다. 따라서 키오스크의 환경 품질은 경험
가치에 정(+)의 영향을 미친다고 할 수 있습니다.

### 2.3.4. 키오스크의 품질 특성은 경험 가치에 유의한 영향을 미칠 것이다.

마지막으로 세 가지 특성을 결합한 품질 특성이 경험 가치에 미치는 영향을
검증하기 위해 다중 선형 회귀 분석을 실시하였습니다.

``` r
verf4 <- lm(value ~ process + outcome + environment)
summary(verf4)
```

    ## 
    ## Call:
    ## lm(formula = value ~ process + outcome + environment)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1.05361 -0.43306  0.04326  0.23292  1.35515 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)   0.5679     0.4254   1.335    0.189    
    ## process       0.2061     0.1516   1.360    0.181    
    ## outcome       0.4935     0.1132   4.361 7.95e-05 ***
    ## environment   0.2345     0.1456   1.611    0.115    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.5843 on 43 degrees of freedom
    ## Multiple R-squared:  0.6266, Adjusted R-squared:  0.6005 
    ## F-statistic: 24.05 on 3 and 43 DF,  p-value: 2.707e-09

위의 분석 결과는 종속변수인 value와 독립변수인 process, outcome,
environment 간의 선형회귀모델의 결과를 나타냅니다. outcom이 value에 대해
통계적으로 유의미한 영향을 미치며, process와 environment는 통계적으로
유의미한 영향을 미치지 않는 것으로 나타났습니다. 전체 모델의 설명력은
0.6005로 모델이 데이터를 약 60.05% 정도 설명할 수 있음을 의미합니다.\
process와 environment의 경우 단순회귀에서와 다르게 다중회귀에서는
유의하지 않다고 나타난 이유는, 다중선형회귀에서는 하나의 독립변수가 더
많은 정보를 설명해줄 수 있기에 다른 변수와 함께 고려될 때에는 더 이상
중요한 영향을 미치지 않을 수 있기 때문입니다.

### 2.3.5. 키오스크 이용에 대한 경험가치는 만족에 정(+)의 영향을 미칠 것이다.

키오스크 경험 가치(value)가 만족(satisfaction)에 미치는 영향을 검증하기
위해 단순 선형 회귀를 사용하였습니다.

``` r
verf5 <- lm(satisfaction ~ value)
summary(verf5)
```

    ## 
    ## Call:
    ## lm(formula = satisfaction ~ value)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1.22619 -0.43912  0.04852  0.44000  1.25734 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)   1.0338     0.3659   2.825  0.00702 ** 
    ## value         0.7253     0.0951   7.626 1.21e-09 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.5963 on 45 degrees of freedom
    ## Multiple R-squared:  0.5638, Adjusted R-squared:  0.5541 
    ## F-statistic: 58.16 on 1 and 45 DF,  p-value: 1.212e-09

단순회귀분석 결과 독립변수인 value가 종속변수인 satisfaction에 유의한
영향을 미치는 것을 알 수 있습니다. 회귀계수는 0.7253, Adjusted
R-squared는 0.5541로 나타났습니다. 따라서 키오스크의 경험 가치가 만족에
정(+)의 영향을 미친다고 할 수 있습니다.

### 2.3.6. 키오스크에 대한 만족은 지속 사용에 정(+)의 영향을 미칠 것이다.

마지막으로 키오스크에 대한 만족(satisfaction)이 지속 사용
의도(continuous)에 미치는 영향을 검증하기 위해 단순 선형 회귀를
사용하였습니다.

``` r
verf6 <- lm(continuous ~ satisfaction)
summary(verf6)
```

    ## 
    ## Call:
    ## lm(formula = continuous ~ satisfaction)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1.20457 -0.39001 -0.05239  0.43904  1.07409 
    ## 
    ## Coefficients:
    ##              Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)    0.7533     0.3720   2.025   0.0488 *  
    ## satisfaction   0.7932     0.0967   8.202 1.75e-10 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.5857 on 45 degrees of freedom
    ## Multiple R-squared:  0.5992, Adjusted R-squared:  0.5903 
    ## F-statistic: 67.28 on 1 and 45 DF,  p-value: 1.753e-10

단순회귀분석 결과 독립변수인 satifaction이 종속변수인 continuous에
유의한 영향을 미치는 것을 알 수 있습니다. 회귀계수는 0.7932, Adjusted
R-squared는 0.5903으로 나타났습니다. 따라서 키오스크에 대한 만족이 지속
사용 의도에 정(+)의 영향을 미친다고 할 수 있습니다.

# 3. 프로젝트 결과

## 3.1. 가설 검증 결과 요약
![png](https://eunju-choe.github.io/assets/img/posts/20230407/result.png)

가설 검증 결과를 요약하면 다음 사진과 같습니다. 분석 전에
설정한 모든 가설을 수용할 수 있었습니다. 
## 3.2. 결론 키오스크의 품질
특성은 경험 가치에 유의한 정의 영향을 미치는 것을 확인할 수 있었습니다.
특히 결과 품질이 경험 가치에 유의한 영향을 미치는 것을 확인할 수
있습니다. 이를 통해 고객의 경험 가치를 향상시키지 위해, 키오스크 이용 후
결과를 의미하는 결과 품질을 개선하기 위해 집중할 필요가 있습니다. 하지만
과정 품질과 환경 품질 역시 단순 선형 회귀에서는 경험 가치에 유의한
영향을 미친다고 나타났기때문에, 무시할 수는 없다고 할 수 있습니다. \
또한 키오스크의 경험 가치는 키오스크 이용 만족도에 유의한 정의 영향을 미치며,
키오스크의 이용 만족도는 지속 사용 의도에 유의한 정의 영향을 미치는 것을
확인할 수 있었습니다. 다시 말해, 고객의 키오스크 경험 가치를 제고하여
이용 만족도를 높일 수 있으며, 키오스크 이용 만족도의 향상은 지속 사용
의도 향상으로 이어질 수 있습니다. 
## 3.3. 제안
키오스크의 경험 가치 향상은 이용 만족도와, 지속 사용 의도 향상에 영향을 주는 것을 알 수
있었습니다. 따라서 키오스크 이용 만족도와 지속 사용 의도 향상을 위해,
고객의 피드백을 수집하고 결과 품질에 문제가 있는 부분을 파악하여
개선하는 등의 접근이 필요합니다. 자원이 풍부한 경우에는 과정 품질과 환경
품질 역시 꾸준히 문제를 파악하고 개선할 수 있습니다. 이를 위해
키오스크는 꾸준한 피드백 수집과 분석을 위해 고객 설문 조사나 키오스크
이용 기록을 활용하여 데이터를 수집하고 분석하는 프로세스를 구축할 필요가
있습니다.
